# Generated by Django 2.2.15 on 2020-10-25 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201024_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_heading',
        ),
    ]
