# Generated by Django 2.2.15 on 2020-10-25 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_question_question_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user_posted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Profile'),
        ),
    ]
