# Generated by Django 2.2.15 on 2020-10-31 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201025_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='followering',
            new_name='following',
        ),
        migrations.AlterField(
            model_name='answer',
            name='time_post',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_post',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
